version: '3.8'

services:
  demo-blazor:
    image: mycompanyname/demo-blazor:latest
    container_name: demo-blazor
    build:
      context: ../../
      dockerfile: src/Demo.Blazor/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__SelfUrl=https://localhost:44308
      - AuthServer__RequireHttpsMetadata=false  
      - AuthServer__Authority=http://demo-blazor
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Demo;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;Persist Security Info=True;
    ports:
      - "44308:443"
    depends_on:
      - db-migrator
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  db-migrator:
    image: mycompanyname/demo-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Demo.DbMigrator/Dockerfile.local
    environment:
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Demo;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;Persist Security Info=True;
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network    
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network  
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
volumes:
  sqldata:
    name: demo_sqldata
networks:
  abp-network:
    name: demo-network
    driver: bridge